/**
 * Verified mingcute icon names.
 *
 * Every constant here was checked against `@iconify-json/mingcute` — the app uses
 * mingcute exclusively, and an unverified name would silently fall back.
 * Feature code should import from here rather than hand-writing names.
 */
export const ICONS = {
  /* chrome + navigation */
  sidebarToggle: 'layout-left-line',
  panelRight: 'layout-right-line',
  assistant: 'sparkles-line',
  settings: 'settings-1-line',
  search: 'search-2-line',
  add: 'plus-line',
  close: 'close-line',
  check: 'check-line',
  more: 'more-1-line',
  moreVertical: 'dots-vertical-line',
  chevronDown: 'down-small-line',
  chevronRight: 'right-small-line',
  chevronUp: 'up-small-line',
  chevronLeft: 'left-small-line',
  arrowDown: 'arrow-down-line',
  arrowRight: 'arrow-right-line',
  arrowLeft: 'arrow-left-line',
  home: 'home-1-line',
  menu: 'menu-line',
  drag: 'transfer-vertical-line',

  /* window controls */
  minimize: 'minimize-line',
  maximize: 'square-line',
  restore: 'copy-2-line',

  /* workspace */
  project: 'folder-line',
  projectAdd: 'folder-2-line',
  page: 'file-line',
  pageAdd: 'document-2-line',
  document: 'document-line',
  note: 'notebook-line',
  starring: 'star-line',
  starFill: 'star-fill',
  bookmark: 'bookmark-line',
  pin: 'pin-line',
  archive: 'archive-line',
  inbox: 'inbox-line',

  /* editing */
  edit: 'edit-line',
  editPen: 'edit-2-line',
  copy: 'copy-line',
  duplicate: 'copy-line',
  delete: 'delete-line',
  trash: 'delete-2-line',
  undo: 'history-line',
  redo: 'history-anticlockwise-line',
  filter: 'filter-line',
  sort: 'sort-ascending-line',
  move: 'move-line',
  link: 'link-line',
  externalLink: 'external-link-line',
  attach: 'attachment-line',
  export: 'file-export-line',
  download: 'download-line',
  upload: 'upload-line',
  image: 'photo-album-line',
  camera: 'camera-line',

  /* formatting */
  bold: 'bold-line',
  italic: 'italic-line',
  underline: 'underline-line',
  strikethrough: 'strikethrough-line',
  code: 'code-line',
  inlineCode: 'code-line',
  quote: 'quote-left-line',
  blockquote: 'blockquote-line',
  heading1: 'heading-1-line',
  heading2: 'heading-2-line',
  heading3: 'heading-3-line',
  text: 'text-line',
  paragraph: 'paragraph-line',
  list: 'list-ordered-line',
  checklist: 'checkbox-line',
  bulletList: 'list-check-line',
  table: 'table-line',
  divider: 'border-horizontal-line',
  callout: 'information-line',
  highlight: 'text-color-line',
  font: 'font-line',

  /* data */
  dashboard: 'dashboard-line',
  chartBar: 'chart-bar-line',
  chartLine: 'chart-line-line',
  chartPie: 'chart-pie-line',
  chartDonut: 'donut-line',
  chartHorizontal: 'chart-horizontal-line',
  metric: 'percentage-line',
  timeline: 'timeline-line',
  calendar: 'calendar-line',
  time: 'time-line',
  clock: 'clock-2-line',
  target: 'target-line',
  layers: 'layers-line',
  grid: 'grid-line',
  grid2: 'grid-2-line',
  columns: 'column-line',
  layout: 'layout-line',
  box: 'box-line',
  components: 'components-line',
  progress: 'loading-2-line',

  /* media */
  gallery: 'album-line',
  play: 'play-line',
  music: 'music-2-line',
  video: 'video-line',
  microphone: 'microphone-line',

  /* assistant */
  send: 'send-line',
  stop: 'stop-line',
  chat: 'chat-1-line',
  message: 'message-1-line',
  refresh: 'refresh-1-line',
  loading: 'loading-3-line',
  sparkles: 'sparkles-line',
  sparkles2: 'sparkles-2-line',
  ai: 'ai-line',
  brain: 'brain-line',
  robot: 'robot-line',
  magic: 'magic-1-line',
  bulb: 'bulb-line',
  rocket: 'rocket-line',
  history: 'history-line',

  /* status + providers */
  info: 'information-line',
  success: 'check-circle-line',
  warning: 'warning-line',
  alert: 'alert-line',
  error: 'close-circle-line',
  shield: 'shield-line',
  key: 'key-1-line',
  lock: 'file-locked-line',
  plug: 'plugin-line',
  server: 'server-line',
  terminal: 'terminal-line',
  eye: 'eye-line',
  eyeOff: 'eye-close-line',
  user: 'user-1-line',
  team: 'group-2-line',
  tag: 'hashtag-line',
  flag: 'flag-1-line',
  sun: 'sun-line',
  moon: 'moon-line',
  monitor: 'monitor-line',
  palette: 'palette-line',
  contrast: 'palette-2-line',
  flame: 'flame-line',
  zap: 'lightning-line',
  activity: 'chart-decrease-line',
  refresh2: 'refresh-2-line',
  external: 'external-link-line',
  dots: 'dots-line',
  fullscreen: 'fullscreen-line',
  // fallback used by the Icon component
  fallback: 'box-line'
} as const

export type IconName = (typeof ICONS)[keyof typeof ICONS]
